<!doctype html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/style.css">
    <title>Pixel SVG Avatar!</title>
    <script src="js/app.js" type="module" async defer></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
    <main class="row">
        <section id="avatar-container" class="col-sm-12 col-md-7 col-lg-7 col-xl-5">
            <?= $svg; ?>
        </section>
        <form id="generate-avatar-form" action="index.php" method="post" class="col-12">
            <div class="text-center">
                <label for="size-input">Taille</label>
                <input id="size-input" type="range" min="3" max="100" value="<?= $_POST['size'] ?? DEFAULT_SIZE_VALUE ?>" step="1" name="size">
                <output id="size-ouput"></output>
            </div>

            <div class="text-center">
                <label for="colors-input">Couleurs</label>
                <input id="colors-input" type="range" min="2" max="100" value="<?= $_POST['colors'] ?? DEFAULT_COLORS_VALUE ?>" step="1" name="colors">
                <output id="colors-output"></output>
            </div>
            <div class="text-center">
                <input type="hidden" name="action" value="generate">
                <input type="submit" value="Générer">
            </div>
        </form>

        <form id="save-avatar-form" action="index.php" method="post">
            <input type="hidden" name="svg" value="<?= htmlspecialchars($svg) ?>">
            <input type="hidden" name="action" value="save">
            <input type="submit" value="Enregistrer">
        </form>

        <form id="download-avatar-form" action="index.php" method="post">
            <input type="hidden" name="svg" value="<?= htmlspecialchars($svg) ?>">
            <input type="hidden" name="action" value="download">
            <input type="submit" value="Télécharger">
        </form>
    </main>
</body>

</html>